[versions]
accompanistFlowlayout = "0.36.0"
accompanistPagerVersion = "0.36.0"
activityCompose = "1.10.1"
agp = "8.9.1"
androidImageCropper = "4.6.0"
androidxCredentials = "1.5.0"
androidxJunit = "1.1.5"
appauthVersion = "0.11.1"
appUpdate = "2.1.0"
appUpdateKtx = "2.1.0"
barcodeScanning = "17.3.0"
barcodeScanningCommon = "17.0.0"
billingKtx = "7.1.1"
biometric = "1.1.0"
cameraCamera2 = "1.4.1"
cameraLifecycle = "1.4.2"
cameraView = "1.4.1"
coilCompose = "2.7.0"
comGoogleAndroidPlayReview = "2.0.2"
comGoogleAndroidPlayReviewKtx = "2.0.2"
commonmarkVersion = "0.24.0"
composeBom = "2025.03.00"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
firebaseFirestore = "25.1.3"
firebaseMessaging = "24.1.1"
generativeai = "0.9.0"
googleCore = "3.5.3"
googleServicesVersion = "4.4.2"
gson = "2.12.1"
imageLabelingVersion = "17.0.9"
javaxMail = "1.6.2"
journeyappsZxingAndroidEmbedded = "4.3.0"
json = "20250107"
junit = "4.13.2"
kotlin = "2.0.0"
lifecycleRuntimeKtx = "2.8.7"
material = "1.12.0"
navigationCompose = "2.8.9"
navigationRuntimeKtx = "2.8.9"
okhttp = "5.0.0-alpha.14"
playServicesBase = "18.6.0"
playServicesIdentity = "18.1.0"
playServicesMlkitImageLabelingVersion = "16.0.8"
playServicesMlkitTextRecognition = "19.0.1"
playServicesMlkitTextRecognitionCommon = "19.1.0"
runtimeLivedata = "1.7.8"
tensorflowLite = "2.17.0"
textRecognition = "16.0.1"
googleid = "1.1.1"
runner = "1.6.2"
playServicesAuth = "21.3.0"
firebaseCommonKtx = "21.0.0"
firebaseAuthKtx = "23.2.0"
firebaseBom = "33.11.0"
firebaseAuth = "23.2.0"
firebaseUiAuth = "9.0.0"
firebaseAnalytics = "22.4.0"
firebaseFirestoreKtx = "25.1.3"
hilt = "2.55"
hilt-navigation-compose = "1.2.0"
imageLabelingCommon = "18.1.0"
firebaseMessagingKtx = "24.1.1"
litertSupportApi = "1.2.0"

[libraries]
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
com-google-android-play-review-ktx2 = { module = "com.google.android.play:review-ktx", version.ref = "comGoogleAndroidPlayReviewKtx" }
com-google-android-play-review2 = { module = "com.google.android.play:review", version.ref = "comGoogleAndroidPlayReview" }
com-journeyapps-zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "journeyappsZxingAndroidEmbedded" }
commonmark-commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmarkVersion" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
gms-google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
gms-play-services-mlkit-image-labeling = { module = "com.google.android.gms:play-services-mlkit-image-labeling", version.ref = "playServicesMlkitImageLabelingVersion" }
google-accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPagerVersion" }
google-accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPagerVersion" }
google-core = { module = "com.google.zxing:core", version.ref = "googleCore" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javax-mail = { module = "com.sun.mail:javax.mail", version.ref = "javaxMail" }
mlkit-image-labeling = { module = "com.google.mlkit:image-labeling", version.ref = "imageLabelingVersion" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
json = { group = "org.json", name = "json", version.ref = "json" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanistFlowlayout" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcodeScanning" }
play-services-identity = { module = "com.google.android.gms:play-services-identity", version.ref = "playServicesIdentity" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref = "textRecognition" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-playServicesAuth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
appauth = { module = "net.openid:appauth", version.ref = "appauthVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServicesBase" }
play-services-mlkit-text-recognition-common = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-common", version.ref = "playServicesMlkitTextRecognitionCommon" }
play-services-mlkit-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognition" }
barcode-scanning-common = { group = "com.google.mlkit", name = "barcode-scanning-common", version.ref = "barcodeScanningCommon" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-ui-auth = { group = "com.firebaseui", name = "firebase-ui-auth", version.ref = "firebaseUiAuth" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
image-labeling-common = { group = "com.google.mlkit", name = "image-labeling-common", version.ref = "imageLabelingCommon" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
litert-support-api = { group = "com.google.ai.edge.litert", name = "litert-support-api", version.ref = "litertSupportApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationCompose" }