title: FreshKeeper
description: A mobile app that helps users track food expiration dates and minimize waste. Timely reminders for smarter consumption habits.
markdown: kramdown
theme: minima

header_pages:
  - terms-of-service.md
  - privacy-policy.md
  - imprint.md

locale: "de-DE"
lang: "de"
timezone: "Europe/Berlin"

plugins:
  - jekyll-seo-tag

minima:
  skin: dark
  custom_css:
    - /assets/css/custom.css
